import type { Metadata } from "next";
import "./globals.css";
import { ProgressBar as ProgressBarProvider } from "@/providers/ProgressBar";
import Header from "@/components/Header";
import { HTMLAttributes } from "react";
import BodyTag from "@/components/BodyTag";
import ReduxStoreProvider from "@/providers/ReduxStore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxStoreProvider>
      <html lang="en">
        <BodyTag>
          <ProgressBarProvider className="bg-green-400 h-[3px] ">
            <Header />
            {children}
          </ProgressBarProvider>
        </BodyTag>
      </html>
    </ReduxStoreProvider>
  );
}


